### ISSUE TITLE
Course review

### ISSUE THREAD

**Issue by romanlesnoy** [Anton-Kumachev/YLab_UNIVERSITY#1]
Привет! 
Прошу прошения, если побеспокоил здесь. Мне предложили пройти курс YLab University. Мне нужно ревью о курсе. Что можешь о них сказать?

**Comment by Anton-Kumachev** [comment]
Привет, Роман!
Я пробовал проходить курс в феврале этого года. На тот момент на начальном этапе было много желающих.
Лекции идут раз в неделю, на неделю дают д/з, кто делает его в срок, тот получает доступ к следующей лекции.
Когда это было в феврале, к сожалению, курс был очень сырой, позиционировался он на базе выкачанных текстовых уровней
Javarush, но далее каждая лекция была — с виду чистая импровизация лектора. Материал подавался обзорно и не по тем темам,
которые нужно было проходить по уровням д/з.
Таким образом, цель данного курса не научить тебя всему, что было бы полезно, а выявить сильных или хорошо подготовленных 
начинающих джваистов. На тот момент я таким уровнем не обладал, поэтому дальше третьей лекции не прошёл.
Если ты обладаешь уверенными знаниями по Java SE, то можно пробовать и возможно удастся попасть на стажировку и возьмут на работу.
Но будь готов в коротки сроки осваивать какие-то материалы на ходу. Что там придумают уж не знаю)
Я так понял, цель у устроителей именно в том, чтобы найти способных или лучших новичков и взять их на работу, чтобы в дальнейшем они развивались 
вместе с компанией.
Наверняка компания преследует и другие цели, но мне о них конечно же не известно, дальше можно пофантазировать, если есть желание)
 
 
 
--
С уважением, Антон Кумачёв

**Comment by romanlesnoy** [comment]
Спасибо  за отзыв. Приму к сведению

**Comment by Anton-Kumachev** [comment]
Желаю успехов, Роман!
